name = "PhylogeneticTrees"
uuid = "1e97b59f-0837-4bde-8329-875b703414d1"
authors = ["BT Kopperud"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
